# GitHub Actions 的名称
name: GitHub Actions Publish To Tencent Docker
# 当 master 分支发生 push 或者 pull request 事件时触发 action
on:
  # 支持手动触发构建
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
# 指定 jobs
jobs:
  # build job
  build:
    # 指定运行在 ubuntu 上
    runs-on: ubuntu-latest
    steps:
    # 把仓库代码拉到 ubuntu 镜像上
    - uses: actions/checkout@v2
    # 指定 java 版本
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
          java-version: 1.8
    # 通过 gradle 打包我们的项目
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    # 通过 Dockerfile 构建镜像
    - name: Build docker image
      run: docker build . --file Dockerfile --tag ccr.ccs.tencentyun.com/private_3389/${$GITHUB_REPOSITORY##*/}
    # 登录腾讯的 docker 镜像仓库
    - name: Login to tencnet docker image registry
      run: echo "${{ secrets.TENCENT_REGISTRY_PASSWORD }}" |  docker login --username=100006496732 ccr.ccs.tencentyun.com --password-stdin
    # 把构建好的镜像推送到腾讯仓库
    - name: Push image to tencent docker image registry
      run: docker push ccr.ccs.tencentyun.com/private_3389/fsgplus-tools